'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Bill } from '@/types';
import { ReceiptPreviewModal, BillData } from '@/components/pos/ReceiptPreviewModal';
import { useCafeConfig } from '@/hooks/useCafeConfig';

interface DashboardMetrics {
  totalBills: number;
  grossSales: number;
  totalDiscounts: number;
  totalTax: number;
  netRevenue: number;
  avgTicket: number;
}

interface PaymentItem {
  payment_mode: string;
  count: number;
  amount: number;
}

interface ItemSale {
  name: string;
  qty: number;
  revenue: number;
}

export default function OwnerDashboardPage() {
  const { config } = useCafeConfig();
  const [metrics, setMetrics] = useState<DashboardMetrics>({
    totalBills: 0,
    grossSales: 0,
    totalDiscounts: 0,
    totalTax: 0,
    netRevenue: 0,
    avgTicket: 0,
  });

  const [paymentBreakdown, setPaymentBreakdown] = useState<PaymentItem[]>([]);
  const [topItems, setTopItems] = useState<ItemSale[]>([]);
  const [recentBills, setRecentBills] = useState<Bill[]>([]);
  const [selectedBillData, setSelectedBillData] = useState<BillData | null>(null);
  const [isReceiptOpen, setIsReceiptOpen] = useState(false);
  const [tableStats, setTableStats] = useState<{ occupied: number; total: number }>({ occupied: 0, total: 0 });
  const [setupCompleted, setSetupCompleted] = useState(true);
  
  const [activeShift, setActiveShift] = useState<any>(null);
  const [isShiftLoaded, setIsShiftLoaded] = useState(false);

  useEffect(() => {
    async function loadData() {
      try {
        const [repRes, billsRes, tablesRes, settingRes, shiftRes] = await Promise.all([
          fetch('/api/reports?timeframe=today'),
          fetch('/api/bills'),
          fetch('/api/tables'),
          fetch('/api/settings?key=setup_completed'),
          fetch('/api/shifts'),
        ]);

        const repData = await repRes.json();
        const billsData = await billsRes.json();
        const tablesData = await tablesRes.json();
        const settingData = await settingRes.json();
        
        if (shiftRes.ok) {
           const shiftData = await shiftRes.json();
           if (shiftData.activeShift) setActiveShift(shiftData.activeShift);
        }
        setIsShiftLoaded(true);

        if (repData.summary) setMetrics(repData.summary);
        if (repData.paymentBreakdown) setPaymentBreakdown(repData.paymentBreakdown);
        if (repData.itemSales) setTopItems(repData.itemSales.slice(0, 5));
        if (billsData.bills) setRecentBills(billsData.bills.slice(0, 6));

        if (tablesData.tables && Array.isArray(tablesData.tables)) {
          const total = tablesData.tables.length;
          const occupied = tablesData.tables.filter((t: any) => t.status === 'occupied' || t.status === 'running').length;
          setTableStats({ occupied, total });
        }

        if (settingData && settingData.value !== 'true') {
          setSetupCompleted(false);
        }
      } catch (err) {
        console.error(err);
      }
    }
    loadData();
  }, []);

  const handleRowClick = (b: Bill) => {
    const billData: BillData = {
      billId: b.id,
      orderId: b.orderId,
      tokenNumber: b.tokenNumber || '01',
      restaurantName: config.cafeName || b.restaurantName || 'ChatChaska Cafe',
      gstin: config.gstin || b.gstin || '',
      fssai: config.fssai || b.fssai || '',
      address: config.address || b.address || '',
      date: new Date(b.createdAt).toLocaleString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }),
      tableNumber: b.tableNumber,
      waiterName: b.waiterName,
      customerName: b.customerName,
      customerPhone: b.customerPhone,
      items: b.items.map((i) => ({
        name: i.name,
        quantity: i.quantity,
        unitPrice: i.unitPrice || 0,
        lineTotal: i.lineTotal || 0,
      })),
      subtotal: b.subtotal,
      discountAmount: b.discountAmount,
      cgstRate: config.cgstRate || 2.5,
      sgstRate: config.sgstRate || 2.5,
      cgstAmount: b.cgstAmount,
      sgstAmount: b.sgstAmount,
      grandTotal: b.grandTotal,
      paymentMode: (b.paymentMode || 'CASH').toUpperCase(),
    };
    setSelectedBillData(billData);
    setIsReceiptOpen(true);
  };

  const handleWhatsAppEOD = () => {
    const text = `*Cafe EOD Summary*\nToday's Sales: ₹${metrics.netRevenue}\nBills: ${metrics.totalBills}\nDiscounts: ₹${metrics.totalDiscounts}\nTax: ₹${metrics.totalTax}\n\nGenerated by MenuCraft.`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const totalPaymentSum = paymentBreakdown.reduce((acc, p) => acc + (p.amount || 0), 0) || 1;

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-6 select-none">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-4 border-b border-slate-200/80">
        <div>
          <h1 className="text-2xl font-black text-slate-900 tracking-tight">My Cafe</h1>
          <p className="text-xs text-slate-500 font-medium mt-0.5">
            {new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short', year: 'numeric' })} • Live store overview
          </p>
        </div>
      </div>
      
      {/* Quick Action Bar */}
      <div className="flex flex-wrap items-center gap-3">
        <Link href="/admin/menu" className="bg-white hover:bg-slate-50 text-slate-700 font-bold px-3 py-2 rounded-md text-xs flex items-center gap-1.5 border border-slate-200 shadow-sm transition-all">
          <span className="text-base leading-none">+</span> Add Dish
        </Link>
        <button onClick={handleWhatsAppEOD} className="bg-[#25D366] hover:bg-[#20bd5a] text-white font-bold px-3 py-2 rounded-md text-xs flex items-center gap-1.5 shadow-sm transition-all">
          <span className="text-base leading-none">💬</span> Send WhatsApp EOD
        </button>
        <Link href="/admin/qr-codes" className="bg-white hover:bg-slate-50 text-slate-700 font-bold px-3 py-2 rounded-md text-xs flex items-center gap-1.5 border border-slate-200 shadow-sm transition-all">
          <span className="text-base leading-none">🖨️</span> Table QR Codes
        </Link>
        <Link href="/staff/pos" className="bg-black hover:bg-slate-800 text-white font-bold px-3 py-2 rounded-md text-xs flex items-center gap-1.5 shadow-sm transition-all">
          <span className="text-base leading-none">⚡</span> Open Billing POS
        </Link>
      </div>

      {/* Active Shift Status Widget */}
      {isShiftLoaded && (
        <div className="bg-white border border-slate-200/80 rounded-md p-4 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-md bg-slate-50 border border-slate-100 flex items-center justify-center shrink-0">
              <span className="material-symbols-outlined text-slate-600">storefront</span>
            </div>
            <div>
              <h3 className="font-bold text-sm text-slate-900">Active Shift Status</h3>
              {activeShift ? (
                <div className="flex items-center flex-wrap gap-2 text-xs text-slate-500 mt-0.5">
                  <span className="relative flex h-2 w-2">
                    <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                    <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                  </span>
                  <span>Cashier: <strong className="text-slate-700">{activeShift.cashier_name}</strong></span>
                  <span>•</span>
                  <span>Opening Cash: ₹{activeShift.opening_cash}</span>
                  <span className="text-emerald-600 font-bold ml-1 bg-emerald-50 px-1.5 py-0.5 rounded-sm">Cashier on duty</span>
                </div>
              ) : (
                <div className="text-xs text-slate-500 mt-0.5 flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-rose-500" />
                  No active shift open. POS functions are locked.
                </div>
              )}
            </div>
          </div>
          {!activeShift && (
            <Link href="/staff/shift" className="bg-[#C3A27C] hover:bg-[#B3926C] text-slate-950 font-bold px-4 py-2 rounded-md text-xs transition-all shadow-sm whitespace-nowrap">
              Open Shift →
            </Link>
          )}
        </div>
      )}

      {/* Setup Wizard Incomplete Banner */}
      {!setupCompleted && (
        <div className="bg-[#C3A27C] hover:bg-[#B3926C] text-slate-950 rounded-md p-4 shadow-md flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 animate-in fade-in">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-md bg-white/20 flex items-center justify-center text-xl shrink-0">
              🚀
            </div>
            <div>
              <h3 className="font-bold text-sm">Finish Setting Up Your Cafe Workspace</h3>
              <p className="text-xs text-slate-800">
                Configure your GST/FSSAI numbers, dining tables, and staff PINs in 2 minutes.
              </p>
            </div>
          </div>

          <Link
            href="/admin/setup"
            className="px-4 py-2 bg-white text-slate-950 hover:bg-[#B3926C] hover:text-slate-950 font-black rounded-md text-xs shadow-sm shrink-0 transition-all cursor-pointer"
          >
            Launch Setup Wizard →
          </Link>
        </div>
      )}

      {/* Top Metric Cards */}
      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3.5">
        {/* Card 1: Today's Sales */}
        <div className="p-4.5 bg-white border border-slate-200/80 rounded-md shadow-sm space-y-1.5 xl:col-span-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Today&apos;s Sales</span>
            <div className="flex items-center gap-1.5">
               <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-1.5 py-0.5 rounded-sm flex items-center gap-1">
                 ↑ Live today
               </span>
               <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            </div>
          </div>
          <div className="text-2xl md:text-3xl font-black text-slate-900">₹{metrics.netRevenue}</div>
          <div className="flex items-center justify-between text-[11px] text-slate-500 font-medium pt-1">
             <span>From {metrics.totalBills} completed bills</span>
             <span className="text-slate-700 font-bold bg-slate-100 px-1.5 py-0.5 rounded-sm">Avg: ₹{metrics.avgTicket}</span>
          </div>
        </div>

        {/* Card 2: 7-Day Trend Mini-Chart */}
        <div className="p-4.5 bg-white border border-slate-200/80 rounded-md shadow-sm xl:col-span-1 space-y-3 hidden sm:flex flex-col">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">7-Day Trend</span>
          </div>
          <div className="flex items-end justify-between h-[42px] gap-1 flex-1">
            {[40, 65, 45, 80, 55, 90, 70].map((h, i) => (
              <div key={i} className="flex-1 flex flex-col items-center h-full group">
                <div className="w-full bg-slate-100 rounded-sm h-full relative overflow-hidden flex items-end justify-center">
                  <div 
                    className={`w-full rounded-sm transition-all ${i === 6 ? 'bg-[#C3A27C]' : 'bg-slate-300 group-hover:bg-slate-400'}`} 
                    style={{ height: `${h}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Card 3: Total Bills */}
        <div className="p-4.5 bg-white border border-slate-200/80 rounded-md shadow-sm space-y-1.5 flex flex-col justify-between">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">Total Bills</span>
          <div className="text-2xl md:text-3xl font-black text-slate-900">{metrics.totalBills}</div>
          <div className="text-[11px] text-slate-400 font-medium">Avg Ticket: ₹{metrics.avgTicket}</div>
        </div>

        {/* Card 4: Live Dining */}
        <div className="p-4.5 bg-white border border-slate-200/80 rounded-md shadow-sm space-y-1.5 flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">Live Dining</span>
            <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-sm">LIVE</span>
          </div>
          <div className="text-2xl md:text-3xl font-black text-emerald-600">
            {tableStats.occupied}/{tableStats.total || 8}
          </div>
          <div className="text-[11px] text-slate-400 font-medium">Tables Occupied</div>
        </div>

        {/* Card 5: GST Collected */}
        <div className="p-4.5 bg-white border border-slate-200/80 rounded-md shadow-sm space-y-1.5 flex flex-col justify-between hidden xl:flex">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">GST Collected</span>
          <div className="text-2xl md:text-3xl font-black text-amber-600">₹{metrics.totalTax}</div>
          <div className="text-[11px] text-slate-400 font-medium">CGST + SGST</div>
        </div>

      </div>

      {/* Middle Section: Top Dishes & Payment Modes */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* Top Selling Dishes */}
        <div className="lg:col-span-2 bg-white border border-slate-200/80 rounded-md p-5 shadow-sm space-y-3.5">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div className="flex items-center gap-2">
              <span className="text-base">🔥</span>
              <h2 className="font-bold text-sm text-slate-900">Top Selling Dishes Today</h2>
            </div>
            <Link href="/admin/menu" className="text-xs font-bold text-slate-900 hover:text-blue-700">
              View All Menu →
            </Link>
          </div>

          {topItems.length === 0 ? (
            <div className="text-xs text-slate-400 py-8 text-center font-medium">
              No orders settled yet today. Generate bills on POS to see top sellers!
            </div>
          ) : (
            <div className="space-y-2.5">
              {topItems.map((item, idx) => {
                const maxRevenue = topItems[0]?.revenue || 1;
                const pct = Math.min(100, Math.round((item.revenue / maxRevenue) * 100));

                return (
                  <div key={idx} className="space-y-1">
                    <div className="flex justify-between items-center text-xs">
                      <div className="flex items-center gap-2 font-bold text-slate-800">
                        <span className="w-5 h-5 rounded-full bg-slate-100 text-[10px] flex items-center justify-center font-mono text-slate-500">
                          {idx + 1}
                        </span>
                        <span>{item.name}</span>
                        <span className="text-[11px] text-slate-400 font-normal">×{item.qty} sold</span>
                      </div>
                      <span className="font-extrabold text-slate-900">₹{item.revenue}</span>
                    </div>
                    <div className="w-full bg-slate-100 h-1.5 rounded-full overflow-hidden">
                      <div
                        className="bg-[#C3A27C] h-full rounded-full transition-all duration-500"
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Payment Modes Breakdown */}
        <div className="bg-white border border-slate-200/80 rounded-md p-5 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div className="flex items-center gap-2">
              <span className="text-base">💳</span>
              <h2 className="font-bold text-sm text-slate-900">Payment Modes</h2>
            </div>
          </div>

          {paymentBreakdown.length === 0 ? (
            <div className="text-xs text-slate-400 py-8 text-center font-medium">
              No payments recorded today
            </div>
          ) : (
            <div className="space-y-3">
              {paymentBreakdown.map((pm, idx) => {
                const pct = Math.round((pm.amount / totalPaymentSum) * 100);
                const isUpi = (pm.payment_mode || '').toLowerCase() === 'upi';
                const isCash = (pm.payment_mode || '').toLowerCase() === 'cash';

                return (
                  <div key={idx} className="p-3 bg-slate-50 border border-slate-200/60 rounded-md space-y-1.5">
                    <div className="flex justify-between items-center text-xs">
                      <span className="font-extrabold uppercase tracking-wide text-slate-800 flex items-center gap-1.5">
                        <span>{isUpi ? '📱' : isCash ? '💵' : '💳'}</span>
                        {pm.payment_mode}
                      </span>
                      <span className="font-black text-slate-900">₹{pm.amount}</span>
                    </div>
                    <div className="flex justify-between items-center text-[11px] text-slate-400 font-medium">
                      <span>{pm.count} bills</span>
                      <span>{pct}% of total</span>
                    </div>
                    <div className="w-full bg-slate-200 h-1.5 rounded-full overflow-hidden">
                      <div
                        className={`h-full rounded-full ${isUpi ? 'bg-[#C3A27C]' : isCash ? 'bg-emerald-600' : 'bg-purple-600'}`}
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Bottom Section: Recent Completed Bills */}
      <div className="bg-white border border-slate-200/80 rounded-md overflow-hidden shadow-sm">
        <div className="p-4 border-b border-slate-100 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <span className="text-base">🧾</span>
            <h2 className="font-bold text-sm text-slate-900">Recent Bills Today</h2>
          </div>
          <Link href="/admin/reports" className="text-xs font-bold text-slate-900 hover:text-blue-700">
            View All Sales →
          </Link>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-700">
            <thead className="bg-slate-50/80 text-slate-500 uppercase font-bold border-b border-slate-200/80">
              <tr>
                <th className="p-3">Token</th>
                <th className="p-3">Bill ID</th>
                <th className="p-3">Table</th>
                <th className="p-3">Waiter</th>
                <th className="p-3">Payment</th>
                <th className="p-3 font-bold text-right">Grand Total</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {recentBills.length === 0 ? (
                <tr>
                  <td colSpan={6} className="p-6 text-center text-slate-400 font-medium">
                    No bills generated yet today.
                  </td>
                </tr>
              ) : (
                recentBills.map((b) => (
                  <tr
                    key={b.id}
                    onClick={() => handleRowClick(b)}
                    className="hover:bg-[#C3A27C]/20 cursor-pointer transition-colors"
                  >
                    <td className="p-3 font-mono font-bold text-slate-800">#{b.tokenNumber || '01'}</td>
                    <td className="p-3 font-mono font-semibold text-slate-600">{b.id}</td>
                    <td className="p-3 font-medium">{b.tableNumber}</td>
                    <td className="p-3 text-slate-500">{b.waiterName}</td>
                    <td className="p-3 uppercase font-bold text-[11px] text-amber-600">{b.paymentMode}</td>
                    <td className="p-3 font-black text-slate-900 text-right">₹{b.grandTotal}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Receipt Preview Modal */}
      {isReceiptOpen && selectedBillData && (
        <ReceiptPreviewModal
          isOpen={isReceiptOpen}
          onClose={() => setIsReceiptOpen(false)}
          billData={selectedBillData}
          hideGoBack={true}
          hideWhatsApp={false}
        />
      )}
    </div>
  );
}
